name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Tests práctica 4 (fiados)
        run: node practica-4/fiados.test.js

      - name: Tests práctica 5 (sano)
        run: node practica-5/sano.test.js
